### Reorganização de Arrays

In [1]:
import numpy as np

In [4]:
matriz = np.array([[1,2,3,4], [5,6,7,8]])
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# Desde que tenha o mesmo número de itens dentro do reshape, é valido -> brincar com esses valores
matriz.reshape([2,4])
matriz.reshape([4,2])
matriz.reshape([1,8])

array([[1, 2, 3, 4, 5, 6, 7, 8]])

### Stack de Vetores - Concatenação de vetores de mesma dimensão

In [10]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

# V stack -> o V significa Vertically, um stack vertical
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# H stack -> o H significa Horizontally, um stack horizontal
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
a = np.vstack([v1,v1,v2,v2])
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [21]:
# é possível continuar essa concatenção, só é chamada de stack
np.vstack([a, v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

### Mudança de dtype

In [24]:
a.dtype

dtype('int32')

In [25]:
a = a.astype('float32')
a.dtype

dtype('float32')

### Advanced Indexing

#### Boolean Masking
Em ciência da computação, boolean, ou lógico, é um tipo de dado primitivo que possui dois valores, que podem ser considerados como 0 ou 1, falso ou verdadeiro

In [32]:
dados = np.random.randint(0, 20, size=(5,5))
dados

array([[ 7,  8, 16,  2, 19],
       [18,  8, 14, 16, 14],
       [18,  7,  6, 10,  7],
       [16,  4,  3, 13, 19],
       [11,  5, 19,  9,  8]])

In [33]:
dados > 10

array([[False, False,  True, False,  True],
       [ True, False,  True,  True,  True],
       [ True, False, False, False, False],
       [ True, False, False,  True,  True],
       [ True, False,  True, False, False]])

##### É possível fazer o array utilizando os indexes da mascára que foi criada anteriormente
Então no exemplo abaixo queremos dados onde os dados são maiores que 10

In [37]:
dados[dados > 10]

array([16, 19, 18, 14, 16, 14, 18, 16, 13, 19, 11, 19])

In [43]:
# A função any verifica se qualquer valor bate a requisição
np.any(dados > 10)
# é possível alterar e analisar por linhas e colunas
np.any(dados > 10, axis=0)
np.any(dados > 10, axis=1)

array([ True,  True,  True,  True,  True])

In [44]:
# O oposto da função any é a função all, que só nos retorna true se todos valores no eixo são verdadeiros
np.all(dados > 10)
# é possível alterar e analisar por linhas e colunas
np.all(dados > 10, axis=0)
np.all(dados > 10, axis=1)

array([False, False, False, False, False])

In [47]:
# mais de uma condição
((dados > 10) & (dados < 15)) 
# é possível utilizar a notação NOT ~ negativa
~((dados > 10) & (dados < 15)) 

array([[ True,  True,  True,  True,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

Então é possível acessar os dados via index no numpy, assim como em listas

In [38]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
a[[1, 2, 9]]

array([ 2,  3, 10])

In [40]:
# e note que indexes negativos também são válidos
a[[1,2,-1]] == a[[1, 2, 9]]

array([ True,  True,  True])

### Desafio Final

In [55]:
m = np.arange(1,31).reshape([6,5])
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Questões:
1. Faça um slice que retorne a ultima linha da matriz (utilize indexes negativos)
2. Faça um slice na matriz que retorne uma matriz utilizando os números 19, 20, 24, 25
3. Retorne a média dos valores das ultimas 3 linhas
4. Retorne a diagonal que vai do número 2 até o número 20
5. Queremos o retorno sendo uma matriz do tipo: 

| 4  | 5  |
|---|---|
| 24  | 25  |
| 29  | 30  |

--------------------------------

### Soluções

In [60]:
# 1.
m[-1,]

array([26, 27, 28, 29, 30])

In [59]:
# 2.
m[3:5,-2:]

array([[19, 20],
       [24, 25]])

In [66]:
# 3. 
tres_linhas = m[-3:,:]
resposta = tres_linhas.mean()
resposta
# m[-3:,:].mean()

23.0

In [68]:
# 4.
# indexing com listas, como foi ensinado na ultima aula
m[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [76]:
# 5.
m[[0,4,5]]

array([[ 1,  2,  3,  4,  5],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [77]:
m[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])