In [ ]:
import numpy as np

### Questões:
1. Faça um slice que retorne a ultima linha da matriz (utilize indexes negativos)
2. Faça um slice na matriz que retorne uma matriz utilizando os números 19, 20, 24, 25
3. Retorne a média dos valores das ultimas 3 linhas
4. Retorne a diagonal que vai do número 2 até o número 20
5. Queremos o retorno sendo uma matriz do tipo: 

| 4  | 5  |
|---|---|
| 24  | 25  |
| 29  | 30  |

In [55]:
m = np.arange(1,31).reshape([6,5])
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

--------------------------------

### Soluções

In [60]:
# 1.
m[-1,]

array([26, 27, 28, 29, 30])

In [59]:
# 2.
m[3:5,-2:]

array([[19, 20],
       [24, 25]])

In [66]:
# 3. 
tres_linhas = m[-3:,:]
resposta = tres_linhas.mean()
resposta
# m[-3:,:].mean()

23.0

In [68]:
# 4.
# indexing com listas, como foi ensinado na ultima aula
m[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [76]:
# 5.
m[[0,4,5]]

array([[ 1,  2,  3,  4,  5],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [77]:
m[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])