### Cuidado ao copiar matrizes

In [1]:
import numpy as np
a = np.array([1,2,3])
b = a
b[0] = 256
print(b)

[256   2   3]


In [2]:
print(a)

[256   2   3]


a foi alterada por b, então para copiar um matriz, temos que usar .copy()

In [3]:
import numpy as np
a = np.array([1,2,3])
b = a.copy()
b[0] = 256
print(b)

[256   2   3]


In [4]:
print(a)

[1 2 3]


### Matemática (chatinho novamente, mas necessário)

In [5]:
# element wise operations
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
a + 2

array([3, 4, 5, 6])

In [7]:
a - 2

array([-1,  0,  1,  2])

In [8]:
a * 2

array([2, 4, 6, 8])

In [9]:
a ** 2

array([ 1,  4,  9, 16])

In [10]:
# é possível fazer a atribuição +=
a += 5
a

array([6, 7, 8, 9])

In [12]:
# element wise operations com dois arrays de mesmas dimensões
b = np.array([5, -5, 5, -5])
a - b

array([ 1, 12,  3, 14])

### Operações matemáticas mais complexas

In [18]:
import math

In [26]:
a = np.array([1,2,3,4])
a = a * math.pi
a

array([ 3.14159265,  6.28318531,  9.42477796, 12.56637061])

In [27]:
np.cos(a)

array([-1.,  1., -1.,  1.])

In [28]:
np.sin(a)

array([ 1.2246468e-16, -2.4492936e-16,  3.6739404e-16, -4.8985872e-16])

In [30]:
cc = np.array([[1,2,3], [4,5,6], [7,8,9]])
cc

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
cc[:, -2]

array([2, 5, 8])