### Linear Algebra

In [1]:
import numpy as np

In [2]:
a = np.ones([2,3])
print(a)

b = np.full([3,2], 5)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]


In [3]:
# Retorno de erro se tentamos multiplicar matrizes de tamanhos diferentes
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [7]:
# note inclusive que A x B != B x A
np.matmul(a,b)
# np.matmul(b,a)

array([[15., 15.],
       [15., 15.]])

In [8]:
# Encontrar o determinante
identidade = np.identity(3)
identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Pra quem esta familiarizado com Algebra Linear, sabe que o determinante de uma matriz identidade é = 1
np.linalg.det(identidade)

1.0

In [ ]:
# Existem diversas outras composições matemáticas que não serão importantes pra nós nesse curso, mas é válido dar uma estudada pra quem quiser
# Referência (https://docs.scipy.org/doc/scipy/reference/linalg.html)

### Estatística básica

In [10]:
dados = np.array([[1,2,3], [4,5,6]])
dados

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.min(dados)

1

In [13]:
np.max(dados)

6

In [11]:
# Axis 0 é coluna, axis 1 é linha
print(np.min(dados, axis=0))
print(np.min(dados, axis=1))

[1 2 3]
[1 4]


In [14]:
# Soma
print(np.sum(dados))
print(np.sum(dados, axis=0))

21
[5 7 9]


In [15]:
# Média
np.mean(dados)

3.5