In [ ]:
import numpy as np

### Advanced Indexing

#### Boolean Masking
Em ciência da computação, boolean, ou lógico, é um tipo de dado primitivo que possui dois valores, que podem ser considerados como 0 ou 1, falso ou verdadeiro

In [32]:
dados = np.random.randint(0, 20, size=(5,5))
dados

array([[ 7,  8, 16,  2, 19],
       [18,  8, 14, 16, 14],
       [18,  7,  6, 10,  7],
       [16,  4,  3, 13, 19],
       [11,  5, 19,  9,  8]])

In [33]:
dados > 10

array([[False, False,  True, False,  True],
       [ True, False,  True,  True,  True],
       [ True, False, False, False, False],
       [ True, False, False,  True,  True],
       [ True, False,  True, False, False]])

##### É possível fazer o array utilizando os indexes da mascára que foi criada anteriormente
Então no exemplo abaixo queremos dados onde os dados são maiores que 10

In [37]:
dados[dados > 10]

array([16, 19, 18, 14, 16, 14, 18, 16, 13, 19, 11, 19])

In [43]:
# A função any verifica se qualquer valor bate a requisição
np.any(dados > 10)
# é possível alterar e analisar por linhas e colunas
np.any(dados > 10, axis=0)
np.any(dados > 10, axis=1)

array([ True,  True,  True,  True,  True])

In [44]:
# O oposto da função any é a função all, que só nos retorna true se todos valores no eixo são verdadeiros
np.all(dados > 10)
# é possível alterar e analisar por linhas e colunas
np.all(dados > 10, axis=0)
np.all(dados > 10, axis=1)

array([False, False, False, False, False])

In [47]:
# mais de uma condição
((dados > 10) & (dados < 15)) 
# é possível utilizar a notação NOT ~ negativa
~((dados > 10) & (dados < 15)) 

array([[ True,  True,  True,  True,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

Então é possível acessar os dados via index no numpy, assim como em listas

In [38]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
a[[1, 2, 9]]

array([ 2,  3, 10])

In [40]:
# e note que indexes negativos também são válidos
a[[1,2,-1]] == a[[1, 2, 9]]

array([ True,  True,  True])

### Desafio Final

In [55]:
m = np.arange(1,31).reshape([6,5])
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Questões:
1. Faça um slice que retorne a ultima linha da matriz (utilize indexes negativos)
2. Faça um slice na matriz que retorne uma matriz utilizando os números 19, 20, 24, 25
3. Retorne a média dos valores das ultimas 3 linhas
4. Retorne a diagonal que vai do número 2 até o número 20
5. Queremos o retorno sendo uma matriz do tipo: 

| 4  | 5  |
|---|---|
| 24  | 25  |
| 29  | 30  |

--------------------------------